// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaElecciones.DataAccess;

#nullable disable

namespace SistemaElecciones.DataAccess.Migrations
{
    [DbContext(typeof(SistemaEleccionesDbContext))]
    [Migration("20260206234304_AddTableVotacion")]
    partial class AddTableVotacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaElecciones.Entities.Campania", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Denominacion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<int>("EstadoCampaniaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<bool>("PermiteVotoBlanco")
                        .HasColumnType("bit");

                    b.Property<int?>("usuarioActualizacionId")
                        .HasColumnType("int");

                    b.Property<int>("usuarioCreacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstadoCampaniaId");

                    b.ToTable("Campania", (string)null);
                });

            modelBuilder.Entity("SistemaElecciones.Entities.Candidato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaniaId")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrabajadorId")
                        .HasColumnType("int");

                    b.Property<int?>("usuarioActualizacionId")
                        .HasColumnType("int");

                    b.Property<int>("usuarioCreacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CampaniaId");

                    b.HasIndex("TrabajadorId");

                    b.ToTable("Candidato", (string)null);
                });

            modelBuilder.Entity("SistemaElecciones.Entities.EstadoCampania", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("usuarioActualizacionId")
                        .HasColumnType("int");

                    b.Property<int>("usuarioCreacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EstadoCampania", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Vigente",
                            Estado = true,
                            FechaCreacion = new DateTime(2025, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            usuarioCreacionId = 1
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Finalizado",
                            Estado = true,
                            FechaCreacion = new DateTime(2025, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            usuarioCreacionId = 1
                        });
                });

            modelBuilder.Entity("SistemaElecciones.Entities.Padron", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaniaId")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<bool>("EstadoVoto")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrabajadorId")
                        .HasColumnType("int");

                    b.Property<int?>("usuarioActualizacionId")
                        .HasColumnType("int");

                    b.Property<int>("usuarioCreacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CampaniaId");

                    b.HasIndex("TrabajadorId");

                    b.ToTable("Padron", (string)null);
                });

            modelBuilder.Entity("SistemaElecciones.Entities.Sexo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("usuarioActualizacionId")
                        .HasColumnType("int");

                    b.Property<int>("usuarioCreacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sexo", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Masculino",
                            Estado = true,
                            FechaCreacion = new DateTime(2025, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            usuarioCreacionId = 1
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Femenino",
                            Estado = true,
                            FechaCreacion = new DateTime(2025, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            usuarioCreacionId = 1
                        });
                });

            modelBuilder.Entity("SistemaElecciones.Entities.Trabajador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Celular")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NroDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SexoId")
                        .HasColumnType("int");

                    b.Property<int?>("usuarioActualizacionId")
                        .HasColumnType("int");

                    b.Property<int>("usuarioCreacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SexoId");

                    b.ToTable("Trabajador", (string)null);
                });

            modelBuilder.Entity("SistemaElecciones.Entities.Votacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaniaId")
                        .HasColumnType("int");

                    b.Property<int>("CandidatoId")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("usuarioActualizacionId")
                        .HasColumnType("int");

                    b.Property<int>("usuarioCreacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CampaniaId");

                    b.HasIndex("CandidatoId");

                    b.ToTable("Votaciones");
                });

            modelBuilder.Entity("SistemaElecciones.Entities.Campania", b =>
                {
                    b.HasOne("SistemaElecciones.Entities.EstadoCampania", "EstadoCampania")
                        .WithMany()
                        .HasForeignKey("EstadoCampaniaId")
                        .IsRequired();

                    b.Navigation("EstadoCampania");
                });

            modelBuilder.Entity("SistemaElecciones.Entities.Candidato", b =>
                {
                    b.HasOne("SistemaElecciones.Entities.Campania", "Campania")
                        .WithMany()
                        .HasForeignKey("CampaniaId")
                        .IsRequired();

                    b.HasOne("SistemaElecciones.Entities.Trabajador", "Trabajador")
                        .WithMany()
                        .HasForeignKey("TrabajadorId")
                        .IsRequired();

                    b.Navigation("Campania");

                    b.Navigation("Trabajador");
                });

            modelBuilder.Entity("SistemaElecciones.Entities.Padron", b =>
                {
                    b.HasOne("SistemaElecciones.Entities.Campania", "Campania")
                        .WithMany()
                        .HasForeignKey("CampaniaId")
                        .IsRequired();

                    b.HasOne("SistemaElecciones.Entities.Trabajador", "Trabajador")
                        .WithMany()
                        .HasForeignKey("TrabajadorId")
                        .IsRequired();

                    b.Navigation("Campania");

                    b.Navigation("Trabajador");
                });

            modelBuilder.Entity("SistemaElecciones.Entities.Trabajador", b =>
                {
                    b.HasOne("SistemaElecciones.Entities.Sexo", "Sexo")
                        .WithMany()
                        .HasForeignKey("SexoId")
                        .IsRequired();

                    b.Navigation("Sexo");
                });

            modelBuilder.Entity("SistemaElecciones.Entities.Votacion", b =>
                {
                    b.HasOne("SistemaElecciones.Entities.Campania", "Campania")
                        .WithMany()
                        .HasForeignKey("CampaniaId")
                        .IsRequired();

                    b.HasOne("SistemaElecciones.Entities.Candidato", "Candidato")
                        .WithMany()
                        .HasForeignKey("CandidatoId")
                        .IsRequired();

                    b.Navigation("Campania");

                    b.Navigation("Candidato");
                });
#pragma warning restore 612, 618
        }
    }
}
